version: '3'
services:
# the web application
  web:
  # because not default Dockerfile, instead Dockerfile.dev
  # build has to be defined as shown . = current directory compose file
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]
    
  